name: Build

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'charts/**'
      - 'LICENSE'
      - 'LICENSE-bpf.txt'
      - '.gitignore'
      - '.editorconfig'
      - '.vscode/**'
      - '.githooks/**'
      - '.conform.yaml'
      - '.github/dependabot.yml'
      - '.github/copilot-instructions.md'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/PULL_REQUEST_TEMPLATE.md'
      - '.github/workflows/codeql.yml'
      - '.github/workflows/conform.yml'
      - '.github/workflows/license.yml'
      - '.github/workflows/release.yml'
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'charts/**'
      - 'LICENSE'
      - 'LICENSE-bpf.txt'
      - '.gitignore'
      - '.editorconfig'
      - '.vscode/**'
      - '.githooks/**'
      - '.conform.yaml'
      - '.github/dependabot.yml'
      - '.github/copilot-instructions.md'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/PULL_REQUEST_TEMPLATE.md'
      - '.github/workflows/codeql.yml'
      - '.github/workflows/conform.yml'
      - '.github/workflows/license.yml'
      - '.github/workflows/release.yml'

permissions:
  contents: read

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@58077d3c7e43986b6b15fba718e8ea69e387dfcc # v2.15.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version-file: go.mod
        
      - name: Lint
        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
        with:
          # This version number must be kept in sync with Makefile lint one.
          version: v2.10.1

      - name: Test
        run: go test ./...

      - name: Build Micromize image
        run: docker build -f Dockerfile.micromize .

      - name: Build Sigward image
        run: docker build -f Dockerfile.sigward .
